spring:
  application:
    name: libraryapi
  profiles:
    active: production
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}


management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  override-with-generic-response: false

#production
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
  datasource:
    url: ${DATASOURCE_URL}
